/** @type {import("prettier").Config & import("@ianvs/prettier-plugin-sort-imports").PrettierConfig & import("prettier-plugin-tailwindcss").PluginOptions} */
const config = {
  endOfLine: 'auto',
  singleQuote: true,
  jsxSingleQuote: false,
  trailingComma: 'es5',
  arrowParens: 'always',
  useTabs: false,
  quoteProps: 'as-needed',
  bracketSpacing: true,
  bracketSameLine: false,
  tabWidth: 2,
  semi: false,
  printWidth: 100,
  singleAttributePerLine: false,
  importOrder: [
    '',
    '^(react$)',
    '^(next/(.*)$)|^(next$)',
    '',
    '<THIRD_PARTY_MODULES>',
    '',
    '<TYPES>',
    '<TYPES>^[.]',
    '^types$',
    '^@/types(/.*)$',
    '',
    '^@/generated(/.*)$',
    '',
    '^(@/data|@/constants)(/.*)$',
    '',
    '^(@/lib|@/stores)(/.*)$',
    '',
    '^(@/hooks|@/utils)(/.*)$',
    '',
    '^@/blocks(/.*)$',
    '',
    '^@/components/ui(/.*)$',
    '^@/components(/.*)$',
    '',
    '^@/_refactor(/.*)$',
    '',
    '^[.]',
    '<BUILTIN_MODULES>',
    '',
  ],
  importOrderTypeScriptVersion: '5.2.2',
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  tailwindFunctions: ['cn', 'cva', 'clsx'],
  tailwindAttributes: [],
  plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
}

module.exports = config
